// ============== CHANNELS PANEL ==============

import { Palette, ScrollView } from "std-widgets.slint";
import {
    SidebarPanel,
    PanelListItem,
    PanelEmptyState,
} from "../components/sidebar-panel.slint";

export component ChannelsPanel inherits SidebarPanel {
    title: "Channels";
    search-placeholder: "Search channels";
    show-action-1: false;  // TODO - Missing Implementation: Find channels
    ScrollView {
        vertical-stretch: 1;
        VerticalLayout {
            alignment: start;
            padding: 16px;
            spacing: 16px;
            
            // TODO - Missing Implementation: Channels list
            
            PanelEmptyState {
                vertical-stretch: 1;
                icon: @image-url("../icons/radio.svg");
                title: "TODO - Missing Implementation";
                subtitle: "Channels list will be implemented soon";
            }
        }
    }
}
