// ============== STATUS PANEL ==============

import { Palette, ScrollView } from "std-widgets.slint";
import {
    SidebarPanel,
    PanelListItem,
    PanelEmptyState,
} from "../components/sidebar-panel.slint";

export component StatusPanel inherits SidebarPanel {
    title: "Status";
    search-placeholder: "Search status updates";
    show-action-1: false;  // TODO - Missing Implementation: New status
    ScrollView {
        vertical-stretch: 1;
        VerticalLayout {
            alignment: start;
            padding: 16px;
            spacing: 16px;
            
            // TODO - Missing Implementation: Status list
            
            PanelEmptyState {
                vertical-stretch: 1;
                icon: @image-url("../icons/circle-dashed.svg");
                title: "TODO - Missing Implementation";
                subtitle: "Status list will be implemented soon";
            }
        }
    }
}
